# A sample Gemfile
source "https://rubygems.org"

gem "webmachine", "~> 1.1.0"
gem "json", "~> 1.8.0"
# gem "reel", "~> 0.3.0"

gem "activerecord", "~> 3.2.13"
gem "sqlite3", "~> 1.3.7"

gem "debugger", "~> 1.6.0"
